# Generated by Django 5.1.6 on 2025-02-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('bandera', models.ImageField(blank=True, null=True, upload_to='banderas/')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='directores/')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directores', to='Cines.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Protagonista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='protagonistas/')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protagonistas', to='Cines.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas_peliculas/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailers_peliculas/')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas', to='Cines.director')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='Cines.genero')),
                ('pais_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas', to='Cines.pais')),
                ('protagonistas', models.ManyToManyField(related_name='peliculas', to='Cines.protagonista')),
            ],
        ),
    ]
