# Generated by Django 5.1.6 on 2025-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
